[general]
import = [
    "~/.config/alacritty/themes/themes/xterm.toml"
]

[env]
term = "xterm-256color"

[colors.primary]
background = "0x000000"
foreground = "0xFFFFFF"

[window]
opacity = 0.92

[font]
normal.family = "Source Code Pro"
normal.style = "Regular"
size = 8

